package:
  name: bootc
  version: 1.1.7
  epoch: 0
  description: Boot and upgrade via container images
  target-architecture:
    - x86_64
  copyright:
    - license: Apache-2.0-only

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - /work/melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - /work/packages
    packages:
      - busybox
      - build-base
      - cargo-auditable
      - rust
      - zstd-dev
      - openssl-dev
      - glib-dev
      - ostree-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bootc-dev/bootc.git
      tag: v${{ package.version }}
      expected-commit: f1621fa1770977eedd6a344006760ecb15634b5a

  - runs: |
      cargo auditable build --release --locked
      install -Dm755 -t ${{targets.destdir}}/usr/bin target/release/bootc
      install -Dm755 -t ${{targets.destdir}}/usr/bin target/release/system-reinstall-bootc

  - uses: strip
