package:
  name: composefs
  version: 1.0.8
  epoch: 0
  description: The reliability of disk images, the flexibility of files
  target-architecture:
    - x86_64
  copyright:
    - license: GPL-2.0-or-later OR Apache-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - busybox
      - usrmerge-tool
      - build-base
      - meson
      - fuse3-dev
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/composefs.git
      tag: v${{ package.version }}
      expected-commit: 858ce1b38e1534c2602eb431124b5dca706bc746
      
  - uses: meson/configure
    with:
      opts: |
        --default-library=shared \
        -Dfuse=enabled \
        --prefix=$dest/usr
  - uses: meson/compile
  - uses: meson/install
  - runs: usrmerge-tool -usr-sbin ${{targets.destdir}}
  - uses: strip

subpackages:
  - name: composefs-dev
    description: Headers and dev libraries from composefs
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - composefs
