package:
  name: kernel
  version: 6.13.6
  epoch: 1
  description: The Linux kernel
  target-architecture:
    - x86_64
  copyright:
    - license: GPL-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      # - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - bison
      - flex
      - busybox
      - build-base
      - binutils-dev
      - wolfi-baselayout
      - llvm
      - libelf
      - elfutils
      - elfutils-dev
      - openssl-dev
      - findutils
      - diffutils
      - perl
      - kmod
      - rsync

pipeline:
  - uses: fetch
    with:
      # uri: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{package.version}}.tar.xz
      uri: http://localhost:8000/linux-${{package.version}}.tar.xz
      expected-sha256: de0053cb413d408f20fd1d5788219951b8a4403e5dac1b1d9032090938acd199

  - runs: make -j$(nproc)

subpackages:
  - name: kernel-core
    description: The Linux kernel
    pipeline:
      - runs: |
          kernel_version=$(make kernelversion)
          mkdir -p ${{targets.subpkgdir}}/usr/lib/${kernel_version}
          cp ./arch/${{build.arch}}/boot/bzImage ${{targets.subpkgdir}}/usr/lib/${kernel_version}/vmlinuz
          cp System.map ${{targets.subpkgdir}}/usr/lib/${kernel_version}/System.map
          cp .config ${{targets.subpkgdir}}/usr/lib/${kernel_version}/config

  - name: kernel-modules
    description: Kernel modules
    dependencies:
      runtime:
        - kernel-core
    pipeline:
      - runs: make -j$(nproc) modules_install INSTALL_MOD_PATH=${{targets.subpkgdir}}

  - name: kernel-headers
    description: Kernel headers
    dependencies:
      runtime:
        - kernel-core
    pipeline:
      - runs: make -j$(nproc) headers_install INSTALL_HDR_PATH=${{targets.subpkgdir}}
