package:
  name: kernel
  version: 6.13.8
  epoch: 0
  description: The Linux kernel
  target-architecture:
    - x86_64
  copyright:
    - license: GPL-2.0

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - bison
      - flex
      - busybox
      - build-base
      - binutils-dev
      - wolfi-baselayout
      - llvm
      - libelf
      - elfutils
      - elfutils-dev
      - openssl-dev
      - findutils
      - diffutils
      - perl
      - kmod
      - rsync

pipeline:
  - uses: fetch
    with:
      uri: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{package.version}}.tar.xz
      expected-sha256: 259afa59d73d676bec2ae89beacd949e08d54d3f70a7f8b0a742315095751abb

  - runs: |
      cp kernel/.config .config
      make -j$(nproc)

subpackages:
  - name: kernel-core
    description: The Linux kernel
    pipeline:
      - runs: |
          kernel_version=$(make kernelversion)
          modules_dir=${{targets.subpkgdir}}/usr/lib/modules/${kernel_version}
          mkdir -p $modules_dir 
          install -Dm0644 -t ${modules_dir}/ ./System.map
          install -Dm0644 ./arch/${{build.arch}}/boot/bzImage ${modules_dir}/vmlinuz
          install -Dm0644 ./.config ${modules_dir}/config

  - name: kernel-modules
    description: Kernel modules
    dependencies:
      runtime:
        - kernel-core
    pipeline:
      - runs: |
          make -j$(nproc) modules_install INSTALL_MOD_PATH=${{targets.subpkgdir}}/usr

  - name: kernel-headers
    description: Kernel headers
    dependencies:
      runtime:
        - kernel-core
    pipeline:
      - runs: make -j$(nproc) headers_install INSTALL_HDR_PATH=${{targets.subpkgdir}}/usr
