package:
  name: ostree
  version: 2025.2
  epoch: 0
  description: "Operating system and container binary deployment and upgrades"
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - systemd
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
      - /work/packages
    keyring:
      - ./melange.rsa.pub
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - build-base
      - bison
      - autoconf
      - pkgconf-dev
      - automake
      - libtool
      - xz-dev
      - e2fsprogs-dev
      - fuse3-dev
      - zlib-dev
      - openssl-dev
      - glib-dev
      - gpgme-dev
      - libarchive-dev
      - systemd-dev
      - libselinux-dev
      - curl-dev
      - dracut
      - composefs-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ostreedev/ostree.git
      tag: v${{package.version}}
      expected-commit: 1dd64eb264be462475a1163c6fee686c1f191994

  - runs: env NOCONFIGURE=1 ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --disable-silent-rules \
        --enable-gtk-doc \
        --with-selinux \
        --with-curl \
        --with-openssl \
        --without-soup \
        --with-composefs \
        --with-dracut=yesbutnoconf

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip


subpackages:
  - name: ostree-dev
    description: Headers and dev libraries from ostree
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - ostree
